CREATE TABLE IF NOT EXISTS SUBSCRIBER(
    ID INT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS USERS(
     ID INT PRIMARY KEY,
     CHAT_ID INT NOT NULL UNIQUE,
     NAME VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS STAR(
     ID INT PRIMARY KEY,
     USER_ID INT NOT NULL,
     DONOR_USER_ID INT NOT NULL,
     SPRINT_ID INT NOT NULL,
     DONATION_DATE TIMESTAMP NOT NULL,
     FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT(ID)
);

CREATE TABLE IF NOT EXISTS SPRINT(
     ID INT PRIMARY KEY,
     SPRINT_NUMBER INT NOT NULL,
     START_DATE DATE NOT NULL,
     END_DATE DATE NOT NULL
);

INSERT INTO SPRINT (ID, SPRINT_NUMBER, START_DATE, END_DATE)
VALUES (1, '10', '2024-04-04', '2024-04-18');
